### PR TITLE
Add optional shadow and shine to the title bar

### PR DESCRIPTION
**Pull request by attila-at-hyper**

### CODE REVIEW

**Comment by 3lvis** [comment]
Make sure the assets are copied properly when running `pod install`. We have this in our project.

https://github.com/hyperoslo/Form/blob/master/Form.podspec#L17-L19

All the images are in the `Assets` folder and they are referenced like this

``` objc
UIImage *image = [UIImage imageNamed:@"Form.bundle/calendar"];
```

https://github.com/hyperoslo/Form/blob/50506f655976d69044598fa6c220bae3af1c4506/Source/Cells/Popover/FORMDateFieldCell.m#L138

**Comment by attila-at-hyper** [comment]
@3lvis: does this also apply if the assets are only used in the Example? I didn't plan to include the assets into the pod (but let the user of the pod to provide them). Do you think it'd be better to provide a "default" image in the pod?

**Comment by 3lvis** [comment]
@attila-at-hyper Default sounds better for me, specially for this type of things. Shadow is super generic.

**Comment by attila-at-hyper** [comment]
@3lvis: makes sense, added.

**Comment by attila-at-hyper** [comment]
@3lvis: I've just tested in with Nokkeltall and `[UIImage imageNamed:@"CardStack.bundle/card_shadow"]` seems to work fine.

**Comment by 3lvis** [comment]
Awesome!

**Pull request merged**
